apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: uplog
spec:
  selector:
    matchLabels:
      app: uplog
  template:
    metadata:
      labels:
        app: uplog
    spec:
      containers:
      - name: uplog
        image: k8s.gcr.io/uplog:latest
        imagePullPolicy: Always
        command:
        - /uplog
        - --v=2
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
                                                                          
